-- MySQL Script generated by MySQL Workbench
-- Tue Aug 20 23:44:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema xuanke
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `xuanke` ;

-- -----------------------------------------------------
-- Schema xuanke
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xuanke` DEFAULT CHARACTER SET utf8mb4 ;
USE `xuanke` ;

-- -----------------------------------------------------
-- Table `xuanke`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xuanke`.`course` ;

CREATE TABLE IF NOT EXISTS `xuanke`.`course` (
  `id` INT(11) NOT NULL,
  `coursename` VARCHAR(100) NULL DEFAULT NULL,
  `time` VARCHAR(45) NULL DEFAULT NULL,
  `classroom` VARCHAR(45) NULL DEFAULT NULL,
  `teacherid` INT(11) NULL DEFAULT NULL,
  `teachername` VARCHAR(45) NULL DEFAULT NULL,
  `teachernumber` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `xuanke`.`student selected course item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xuanke`.`student selected course item` ;

CREATE TABLE IF NOT EXISTS `xuanke`.`student selected course item` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `studentid` INT(11) NULL DEFAULT NULL,
  `studentnumber` VARCHAR(45) NULL DEFAULT NULL,
  `studentname` VARCHAR(45) NULL DEFAULT NULL,
  `teachername` VARCHAR(45) NULL DEFAULT NULL,
  `courseid` INT NULL DEFAULT NULL,
  `coursename` VARCHAR(45) NULL DEFAULT NULL,
  `coursetime` VARCHAR(45) NULL DEFAULT NULL,
  `position` VARCHAR(45) NULL DEFAULT NULL,
  `selecttime` VARCHAR(45) NULL DEFAULT NULL,
  `teacherid` INT(11) NULL DEFAULT NULL,
  `teachernumber` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `courseid_idx` (`courseid` ASC),
  INDEX `studentid_idx` (`studentid` ASC),
  INDEX `teacherid_idx` (`teacherid` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `xuanke`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xuanke`.`user` ;

CREATE TABLE IF NOT EXISTS `xuanke`.`user` (
  `id` INT(11) NOT NULL,
  `number` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `type` INT(11) NULL DEFAULT NULL COMMENT '0是学生 1是老师 2是管理员',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
